//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.TotalAmountByAccounts = new HashSet<TotalAmountByAccount>();
        }
    
        public int ID { get; set; }
        public int ConnName_AccountTypeID { get; set; }
        public int UserID { get; set; }
        public bool Active { get; set; }
        public int ConnCredentialsID { get; set; }
    
        public virtual ConnectionCredential ConnectionCredential { get; set; }
        public virtual refConnName_AccountType refConnName_AccountType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TotalAmountByAccount> TotalAmountByAccounts { get; set; }
    }
}
