//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionCredential
    {
        public ConnectionCredential()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int ID { get; set; }
        public int ConnectionID { get; set; }
        public string LoginUsername { get; set; }
        public string LoginPassword { get; set; }
        public string key { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ConnectionName ConnectionName { get; set; }
    }
}
